{
 "title": "Nginx Status",
 "tags": [
  "Web",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(active_connections{job=\"nginx\"},app)"
   },
   {
    "name": "zone",
    "query": "label_values(active_connections{app=\"$app\",job=\"nginx\"},region)"
   },
   {
    "name": "ip",
    "query": "label_values(active_connections{app=\"$app\",region=~\"$zone\",job=\"nginx\"}, HostIP)"
   }
  ]
 },
 "panels": [
  { "title": "intro", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "并发用户数",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(active_connections{app=\"$app\",job=\"nginx\"})"
    }
   ]
  },
  {
   "title": "Curr QPS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(total_requests{app=\"$app\"}[1m]))",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Error Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(accept_connections{app=\"$app\"}) - sum(handled_connections{app=\"$app\"})"
    }
   ]
  },
  {
   "title": "北京时间",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "巴西时间",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "并发数",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(active_connections{app=\"$app\"}) by (region)",
     "legendFormat": "sea"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(total_requests{app=\"$app\"}[1m])) by (region)",
     "legendFormat": "sea"
    }
   ]
  },
  {
   "title": "sea clb network traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clb_intraffic{app=\"$app\",job=\"clb\",region=\"sea\"}",
     "legendFormat": "in"
    },
    {
     "expr": "clb_outtraffic{app=\"$app\",job=\"clb\",region=\"sea\"}",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "us clb network traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "clb_intraffic{app=\"$app\",job=\"clb\",region=\"us\"}",
     "legendFormat": "in"
    },
    {
     "expr": "clb_outtraffic{app=\"$app\",job=\"clb\",region=\"us\"}",
     "legendFormat": "out"
    }
   ]
  },
  { "title": "details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "并发数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(active_connections{app=\"$app\",job=\"nginx\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "clb_intraffic{app=\"$app\",job=\"clb\",region=~\"$zone\"}",
     "legendFormat": "{{region}} {{project}} intraffic({{vip}})"
    },
    {
     "expr": "clb_outtraffic{app=\"$app\",job=\"clb\",region=~\"$zone\"}",
     "legendFormat": "{{region}} {{project}} outtraffic({{vip}})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(total_requests{app=\"$app\"}[1m])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "respones client connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "respones_client_connections{app=\"$app\",job=\"nginx\",HostIP=~\"$ip\"}",
     "legendFormat": "{{HostIP}}"
    }
   ]
  },
  {
   "title": "wait connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wait_connections{app=\"$app\",job=\"nginx\",HostIP=~\"$ip\"}",
     "legendFormat": "{{HostIP}}"
    }
   ]
  },
  {
   "title": "read request headers connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "read_request_headers_connections{app=\"$app\",job=\"nginx\",HostIP=~\"$ip\"}",
     "legendFormat": "{{HostIP}}"
    }
   ]
  },
  {
   "title": "accept connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(accept_connections{app=\"$app\",HostIP=~\"$ip\"}[1m])",
     "legendFormat": "{{HostIP}}"
    }
   ]
  },
  {
   "title": "handled connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(handled_connections{HostIP=~\"$ip\",app=\"$app\"}[1m])",
     "legendFormat": "{{HostIP}}"
    }
   ]
  },
  {
   "title": "total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_requests{app=\"$app\",HostIP=~\"$ip\"}[1m])",
     "legendFormat": "{{HostIP}}"
    }
   ]
  },
  {
   "title": "active connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "active_connections{app=\"$app\",job=\"nginx\",HostIP=~\"$ip\"}",
     "legendFormat": "{{HostIP}}"
    }
   ]
  }
 ]
}